services:
  - type: web
    name: foot-server-api
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_PORT
        sync: false
      - key: CORS_ORIGIN
        value: https://ton-front-end.vercel.app # Remplace par l'URL de ton frontend déployé
    healthCheckPath: /api/health # Optionnel : si vous avez une route de santé